name: turbopanda
channels: 
  - defaults
  - conda-forge
dependencies:
  # required
  - python>=3.8
  - pip>=19.0.3
  - numpy>=1.11.0
  - scipy>=1.3
  - joblib>=0.14.1
  - pandas>=0.25
  - matplotlib>=3.1.1
  - scikit-learn>=0.22
  
  # speed ups
  - numba>=0.48.0

  # progressbars
  - tqdm>=4.48.2

  # for dev.bleep
  - simpleaudio

  # code checks
  - black=20.8b1
  - flake8
  - pre-commit
  - pycodestyle

  # testing
  - pytest
  - hypothesis
