name: turbopanda
channels: 
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip>=19.0.3
  - jupyter>=1.0.0
  - numpy>=1.11.0
  - scipy>=1.3
  - joblib>=0.14.1
  - pandas>=0.25
  - matplotlib>=3.1.1
  - scikit-learn>=0.22
  - numba>=0.48.0
  - statsmodels
  - pip:
      - tqdm