name: turbopanda
channels: 
  - defaults
dependencies:
  - python>=3.6
  - jupyter>=1.0.0
  - numpy>=1.11.0
  - scipy>=1.3
  - pandas>=0.25
  - matplotlib>=3.1.1
  - scikit-learn>=0.21
  - pip>=19.0.3
  - pip:
    - Deprecated
